# Utiliser l'image de base Ubuntu
FROM ubuntu:latest

# Mise à jour des paquets et installation de vsftpd
RUN apt-get update && \
    apt-get install -y vsftpd

# Copier le fichier de configuration vsftpd
COPY vsftpd.conf /etc/vsftpd.conf

# Créer un répertoire pour le FTP et un utilisateur
RUN mkdir -p /ftp && \
    useradd -d /ftp -s /usr/sbin/nologin ftpuser && \
    chown ftpuser:ftpuser /ftp

# Définir le mot de passe pour l'utilisateur ftpuser
RUN echo 'ftpuser:123456789' | chpasswd

# Exposer le port FTP standard et la plage pour le mode passif
EXPOSE 21 21100-21110

# Lancer le serveur FTP avec un message de connexion
CMD echo "Serveur FTP lancé, connectez-vous avec votre client FTP." && vsftpd
