# Création du routeur pro
FROM ubuntu:latest

# Installation des paquets nécessaires
RUN apt-get update && apt-get install -y \
     nano \             
     iputils-ping \    
     net-tools \ 
     iproute2 \        
     iptables 

# Copiez les fichier de configuration dans le container



