version: "3.7"

services:

  voip:
    container_name: voip
    build:
      context: ./voip_pro
      dockerfile: Dockerfile
    restart: always
    hostname: voip
    networks:
      - pro
    privileged: true


  ordi_personnel_pro:
    container_name: ordi_personnel_pro
    build:
      context: ./ordi_personnel_pro
      dockerfile: Dockerfile
    restart: always
    hostname: ordi_personnel_pro
    networks:
      - pro
    privileged: true


networks:

  pro:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 120.0.64.0/20
