FROM debian
RUN apt-get update
RUN apt-get -y install iptables apt-utils iproute2 net-tools systemd telnet nano iputils-ping tcpdump inetutils-traceroute curl isc-dhcp-server
#RUN apt-get -y install quagga
RUN apt-get -f install
RUN apt-get -y install wget
RUN apt-get -y install ftp
#COPY  ./quagga /etc/quagga
#COPY  ./dhcp/dhcpd.conf /etc/dhcp
COPY BOX.sh /BOX.sh
RUN ["chmod", "+x", "BOX.sh"]
RUN mkdir /etc/scripts
ENV PATH "/etc/scripts:$PATH"
#ENTRYPOINT /etc/init.d/quagga start && /bin/bash
ENTRYPOINT  /bin/bash
#ENTRYPOINT ["tail", "-f", "/dev/null"]