# Construction de l'image
FROM andrius/asterisk

# Copiez les fichier de configuration dans le container
COPY ./extensions.conf /etc/asterisk/
COPY ./users.conf /etc/asterisk/
COPY ./asterisk.conf /etc/asterisk/
