# Utilisez une image Ubuntu comme base
FROM ubuntu:18.04

# Mise à jour des packages et installation du serveur DHCP
RUN apt-get update && \
    apt-get install -y isc-dhcp-server

# Copiez votre fichier de configuration DHCP dans le conteneur
COPY dhcpd.conf /etc/dhcp/

# Exposez le port UDP 67 (port DHCP)
EXPOSE 67/udp

# Commande pour démarrer le serveur DHCP
CMD ["/usr/sbin/dhcpd", "-f", "-d", "--no-pid"]