# Création d'un appareil simple avec interface réseau
FROM ubuntu

# Installation des paquets nécessaires pour visualiser les interfaces réseaux
RUN apt-get update && apt-get install -y \
     nano \             
     iputils-ping \    
     net-tools \ 
     iproute2 \        
     iptables 
